### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by Zachary-Rude** [Stamir36/ModernNotyfi#1]
I'm American, and don't understand Russian. You should make an English version.

**Comment by Stamir36** [comment]
Yes, in the near future I will definitely add English

**Comment by Stamir36** [comment]
> Я американец и не понимаю по-русски. Вы должны сделать английскую версию.

English has been added. Click the "Settings" icon - "General options" - "Language".
Update the app via settings if necessary. Version 0.0.1.21
